version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    # Check the npm registry for updates every weekday
    schedule:
      interval: "daily"
    ignore:
      # Does not work with typedoc 0.20.x
      - dependency-name: "typescript"
        versions: ["^4.3.0"]
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every weekday
      interval: "daily"
