name: CI

on:
  push:
    branches:
      - main
    tags:
      - v[0-9]+.[0-9]+.[0-9]+*
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macOS-latest, ubuntu-latest]
        node-version: [10.x, 12.x, 14.x]
    steps:
      - name: Fix git checkout line endings
        run: git config --global core.autocrlf input
      - uses: actions/checkout@v2
      - name: Install platform dependencies
        shell: bash
        run: ci/install_dependencies.sh
      - name: Setup Node.js
        uses: actions/setup-node@v2.1.3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2.1.3
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install
        run: yarn
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn coverage
      - name: Upload code coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage/lcov.info
          env_vars: CI_OS,NODE_VERSION
        env:
          CI_OS: ${{ matrix.os }}
          NODE_VERSION: ${{ matrix.node-version }}

  build-wsl1:
    defaults:
      run:
        shell: wsl-bash {0}
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
    steps:
      - name: Fix git checkout line endings
        run: git config --global core.autocrlf input
        shell: pwsh
      - uses: Vampire/setup-wsl@v1
      - name: WSL kernel version
        run: uname --kernel-release
      - uses: actions/checkout@v2
      - name: Determine WSL version of workspace
        id: wsl-workspace
        run: echo "::set-output name=dir::$(wslpath '${{ github.workspace }}')"
      - name: Move repo to WSL
        run: cp -R ${{ steps.wsl-workspace.outputs.dir }} $HOME/
      - name: Setup Node.js
        run: ci/setup-node-wsl.sh ${{ matrix.node-version }}
      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2.1.3
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: Linux-yarn-${{ hashFiles('**/package.json') }}
          restore-keys: |
            Linux-yarn-
      - name: Install
        run: cd $HOME/cross-spawn-windows-exe && yarn
      - name: Lint
        run: cd $HOME/cross-spawn-windows-exe && yarn lint
      - name: Test
        run: cd $HOME/cross-spawn-windows-exe && CSWE_TEST_FIXTURES=${{ steps.wsl-workspace.outputs.dir }}/test/fixtures yarn coverage && mv coverage ${{ steps.wsl-workspace.outputs.dir }}/
      - name: Upload code coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage/lcov.info
          env_vars: CI_OS,NODE_VERSION
        env:
          CI_OS: WSL
          NODE_VERSION: ${{ matrix.node-version }}
